
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://i11e104.p.ssafy.io:3306/taffy?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: e104_taffy_best

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

  logging:
    level:
      org.hibernate.SQL: debug

jwt:
  key: taffytaffytaffytaffytaffytaffytaffytaffytaffytaffytaffytaffytaffytaffytaffytaffytaffy
  live:
    atk: 1000000
    rtk: 6000000

mail:
  host: smtp.naver.com
  id: dongji_11
  password:
  name: taffy@naver.com
  email: dongji_11@naver.com

  redis:
    port: 6379
    host: i11e104.p.ssafy.io


openvidu:
  url: http://localhost:4443
  secret: MY_SECRET
